project_id = "nxptedmacsdqnehcatpi"

[functions.livekit-token]
verify_jwt = true

[functions.wallet-admin-adjust]
verify_jwt = true

[functions.chat-monitor-search]
verify_jwt = true

[functions.room-microphone]
verify_jwt = true
