"use client";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
type Vip={level:number;title:string;price:number;duration_days:number;benefits:any;is_active:boolean};
export default function VipPage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]); const [rows,setRows]=useState<Vip[]>([]); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 const [form,setForm]=useState<Vip>({level:1,title:"VIP 1",price:1000,duration_days:30,benefits:["شارة VIP"],is_active:true});
 async function load(){const {data,error}=await supabase.from("vip_catalog").select("level,title,price,duration_days,benefits,is_active").order("level");if(error)setError(error.message);else setRows((data??[]) as Vip[])}
 useEffect(()=>{void load()},[]);
 async function save(){setSaving(true);setError("");const {error}=await supabase.from("vip_catalog").upsert({level:Math.floor(form.level),title:form.title.trim(),price:Math.max(0,Math.floor(form.price)),duration_days:Math.max(1,Math.floor(form.duration_days)),benefits:Array.isArray(form.benefits)?form.benefits:[],is_active:form.is_active});if(error)setError(error.message);else await load();setSaving(false)}
 function edit(r:Vip){setForm(r)}
 return <main className="main" dir="rtl"><div className="topbar"><div><a href="/" className="muted">JEHOO CHAT / لوحة التحكم</a><h1>VIP</h1><p className="muted">إدارة مستويات VIP وأسعارها ومدتها ومزاياها.</p></div><a className="secondary" href="/">رجوع</a></div>{error&&<div className="notice error">{error}</div>}
 <section className="panel" style={{maxWidth:900,marginBottom:24}}><h2>إضافة / تحديث مستوى</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div><label>المستوى</label><input className="field" type="number" min="1" max="20" value={form.level} onChange={e=>setForm({...form,level:Number(e.target.value)})}/></div><div><label>الاسم</label><input className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div><label>السعر Coins</label><input className="field" type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div><div><label>المدة بالأيام</label><input className="field" type="number" min="1" value={form.duration_days} onChange={e=>setForm({...form,duration_days:Number(e.target.value)})}/></div><div style={{gridColumn:"1/-1"}}><label>المزايا، مفصولة بفواصل</label><input className="field" value={(form.benefits||[]).join(", ")} onChange={e=>setForm({...form,benefits:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></div></div><label style={{display:"flex",gap:8,margin:"14px 0"}}><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> فعّال</label><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?"جارٍ الحفظ…":"حفظ المستوى"}</button></section>
 <section className="panel"><h2>المستويات الحالية</h2><div style={{display:"grid",gap:8}}>{rows.map(r=><button key={r.level} onClick={()=>edit(r)} style={{textAlign:"right",padding:14,borderRadius:12,border:"1px solid #263342",background:"transparent",color:"inherit"}}><strong>{r.title}</strong><div className="muted">المستوى {r.level} · {Number(r.price).toLocaleString("ar")} Coins · {r.duration_days} يوم · {r.is_active?"فعّال":"موقوف"}</div><div className="muted">{(r.benefits||[]).join(" · ")}</div></button>)}</div></section></main>
}