import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Image, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { supabase } from "@/lib/supabase";

type OfficialMessage = { id:string; title:string; body:string; content_type:string; content_url:string|null; html_content:string|null; created_at:string; pinned:boolean };
export default function OfficialMessagesScreen(){
 const router=useRouter(); const [items,setItems]=useState<OfficialMessage[]>([]); const [busy,setBusy]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{if(!supabase){setBusy(false);return}setBusy(true);const {data,error}=await supabase.from("official_messages").select("id,title,body,content_type,content_url,html_content,created_at,pinned").order("pinned",{ascending:false}).order("created_at",{ascending:false}).limit(100);if(error)setError(error.message);else setItems((data??[]) as OfficialMessage[]);setBusy(false)},[]);
 useEffect(()=>{void load()},[load]);
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ رجوع</Text></Pressable><Text style={s.heading}>الرسائل الرسمية ✅</Text><Pressable onPress={()=>void load()}><Text style={s.back}>تحديث</Text></Pressable></View>
 <ScrollView contentContainerStyle={s.list}>{busy?<ActivityIndicator color="#31D6B0" size="large"/>:error?<Text style={s.error}>{error}</Text>:items.map(m=><View key={m.id} style={s.card}><View style={s.badge}><Text style={s.badgeText}>{m.pinned ? "مثبتة • رسالة رسمية" : "رسالة رسمية"}</Text></View><Text style={s.title}>{m.title}</Text><Text style={s.body}>{m.body}</Text>{m.content_type==="image"&&m.content_url?<Pressable onPress={()=>void Linking.openURL(m.content_url!)}><Image source={{uri:m.content_url}} style={{width:"100%",height:190,borderRadius:12}} resizeMode="contain"/><Text style={s.link}>فتح الصورة ↗</Text></Pressable>:null}{m.content_type==="link"&&m.content_url?<Pressable onPress={()=>void Linking.openURL(m.content_url!)}><Text style={s.link}>فتح الرابط ↗</Text></Pressable>:null}{m.content_type==="html"&&m.html_content?<><Text style={s.htmlNote}>محتوى HTML (يعرض كنص آمن ولا يتم تنفيذه):</Text><Text selectable style={s.htmlCode}>{m.html_content}</Text></>:null}<Text style={s.date}>{new Date(m.created_at).toLocaleString("ar")}</Text></View>)}{!busy&&!error&&!items.length?<Text style={s.empty}>لا توجد رسائل رسمية حالياً.</Text>:null}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#08110F"},header:{padding:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1,borderBottomColor:"#20362F"},heading:{color:"#F2F7FA",fontSize:18,fontWeight:"900"},back:{color:"#31D6B0",fontWeight:"800"},list:{padding:16,gap:14},card:{backgroundColor:"#121F1B",borderColor:"#246452",borderWidth:1,borderRadius:18,padding:16,gap:10},badge:{alignSelf:"flex-start",backgroundColor:"#123C30",paddingHorizontal:10,paddingVertical:6,borderRadius:12},badgeText:{color:"#7BF4D1",fontSize:11,fontWeight:"900"},title:{fontSize:18,fontWeight:"900",color:"#FFFFFF",textAlign:"right"},body:{fontSize:14,lineHeight:23,color:"#D5E4DE",textAlign:"right"},link:{color:"#31D6B0",fontWeight:"900",textAlign:"right"},htmlNote:{color:"#A7BEB5",fontSize:12,textAlign:"right"},htmlCode:{color:"#D5E4DE",fontSize:12,textAlign:"left",backgroundColor:"#09130F",padding:10,borderRadius:8},date:{fontSize:11,color:"#7C968B",textAlign:"right"},error:{color:"#FDA4AF"},empty:{color:"#B6C4D0",textAlign:"center",marginTop:30}});
