import {useEffect,useMemo,useState} from "react";
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {useRouter} from "expo-router";
import {supabase} from "@/lib/supabase";
type Wallet={coins:number;diamonds:number};
type Package={package_key:string;title:string;coins:number;bonus_coins:number;price_usd:number;is_popular:boolean};
type Withdraw={id:string;diamonds:number;amount_usd:number;method:string;status:string;created_at:string};
export default function WalletScreen(){
 const router=useRouter();const client=supabase;const [wallet,setWallet]=useState<Wallet>({coins:0,diamonds:0});const [packages,setPackages]=useState<Package[]>([]);const [withdraws,setWithdraws]=useState<Withdraw[]>([]);const [method,setMethod]=useState("تحويل");const [details,setDetails]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 async function load(){if(!client)return;setError("");const {data:{user}}=await client.auth.getUser();if(!user)return;const [w,p,x]=await Promise.all([client.from("wallets").select("coins,diamonds").eq("user_id",user.id).maybeSingle(),client.from("coin_packages").select("package_key,title,coins,bonus_coins,price_usd,is_popular").eq("is_active",true).order("sort_order",{ascending:true}),client.from("withdraw_requests").select("id,diamonds,amount_usd,method,status,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(20)]);if(w.error||p.error||x.error)setError((w.error||p.error||x.error)?.message||"تعذر التحميل");setWallet({coins:Number(w.data?.coins||0),diamonds:Number(w.data?.diamonds||0)});setPackages((p.data??[]) as Package[]);setWithdraws((x.data??[]) as Withdraw[])}
useEffect(()=>{void load()},[]);
async function recharge(key:string){if(!client)return;setBusy(true);const idempotency="recharge-"+key+"-"+Date.now();const {data,error}=await client.rpc("jehoo_create_recharge_order",{p_package_key:key,p_idempotency_key:idempotency});setBusy(false);if(error){Alert.alert("الشحن",error.message);return}Alert.alert("تم إنشاء الطلب","طلب الشحن قيد المراجعة من الإدارة. Coins ستصل بعد تأكيد الدفع.");}
async function withdraw(){if(!client)return;const amount=Math.floor(Number(wallet.diamonds));if(amount<=0){Alert.alert("السحب","لا يوجد Diamonds للسحب.");return}if(!details.trim()){Alert.alert("السحب","اكتب بيانات وسيلة السحب.");return}setBusy(true);const {data,error}=await client.rpc("jehoo_request_withdraw",{p_diamonds:amount,p_method:method,payout_details:{details:details.trim()}});setBusy(false);if(error){Alert.alert("السحب",error.message);return}Alert.alert("تم الطلب","تم إنشاء طلب السحب بقيمة $"+Number(data?.amount_usd||0).toFixed(2));await load()}
return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><View style={s.head}><Pressable onPress={()=>router.back()}><Text style={s.back}>رجوع</Text></Pressable><Text style={s.title}>المحفظة</Text></View><View style={s.balance}><View><Text style={s.balanceLabel}>Coins</Text><Text style={s.coins}>{wallet.coins.toLocaleString("ar")}</Text></View><View><Text style={s.balanceLabel}>Diamonds</Text><Text style={s.diamonds}>{wallet.diamonds.toLocaleString("ar")}</Text></View></View>
<Text style={s.section}>شحن Coins</Text><Text style={s.hint}>اختر الباقة، ثم يُنشأ طلب شحن وتؤكد الإدارة الدفع.</Text><View style={s.grid}>{packages.map(p=><Pressable key={p.package_key} disabled={busy} onPress={()=>void recharge(p.package_key)} style={s.card}><Text style={s.cardTitle}>{p.title}</Text><Text style={s.cardCoins}>{(Number(p.coins)+Number(p.bonus_coins)).toLocaleString("ar")} Coins</Text><Text style={s.price}>{"$"}{Number(p.price_usd).toFixed(2)}</Text>{p.is_popular?<Text style={s.popular}>الأكثر طلباً</Text>:null}</Pressable>)}</View>
<Text style={s.section}>السحب</Text><Text style={s.hint}>قيمة السحب تُحسب من إعدادات الاقتصاد في الداشبورد، ولا تظهر نسبة التطبيق للمستخدم.</Text><TextInput value={method} onChangeText={setMethod} placeholder="وسيلة السحب" placeholderTextColor="#75998F" style={s.input}/><TextInput value={details} onChangeText={setDetails} placeholder="بيانات التحويل / الحساب" placeholderTextColor="#75998F" style={s.input}/><Pressable disabled={busy} onPress={()=>void withdraw()} style={s.withdraw}><Text style={s.withdrawText}>{busy?"جارٍ التنفيذ…":"طلب سحب كل Diamonds الحالية"}</Text></Pressable>
<Text style={s.section}>طلبات السحب السابقة</Text>{withdraws.map(x=><View key={x.id} style={s.row}><Text style={s.rowMain}>{Number(x.diamonds).toLocaleString("ar")} Diamonds · {"$"}{Number(x.amount_usd).toFixed(2)}</Text><Text style={s.rowSub}>{x.method} · {x.status} · {new Date(x.created_at).toLocaleString("ar")}</Text></View>)}{!withdraws.length?<Text style={s.hint}>لا توجد طلبات سحب.</Text>:null}{error?<Text style={s.error}>{error}</Text>:null}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F4F7F6"},content:{padding:20,paddingBottom:40,gap:10},head:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",marginBottom:8},back:{color:"#157A68",fontWeight:"900"},title:{color:"#153A34",fontSize:22,fontWeight:"900"},balance:{backgroundColor:"#0B493B",borderRadius:20,padding:18,flexDirection:"row-reverse",justifyContent:"space-around",marginBottom:8},balanceLabel:{color:"#A8DCD0",fontSize:12,textAlign:"center"},coins:{color:"#FFF0A6",fontSize:24,fontWeight:"900",textAlign:"center",marginTop:3},diamonds:{color:"#B9FFF0",fontSize:24,fontWeight:"900",textAlign:"center",marginTop:3},section:{color:"#153A34",fontSize:18,fontWeight:"900",textAlign:"right",marginTop:12},hint:{color:"#67877F",fontSize:12,textAlign:"right",lineHeight:19},grid:{flexDirection:"row-reverse",flexWrap:"wrap",gap:10},card:{width:"48%",backgroundColor:"#FFF",borderRadius:16,padding:14,borderWidth:1,borderColor:"#D9E5E1",gap:5},cardTitle:{color:"#193D36",fontWeight:"900",textAlign:"right"},cardCoins:{color:"#157A68",fontSize:14,fontWeight:"900",textAlign:"right"},price:{color:"#5B6F69",fontWeight:"800",textAlign:"right"},popular:{color:"#B17A00",fontSize:10,fontWeight:"900",textAlign:"right"},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:"#D4E2DE",borderRadius:12,padding:12,color:"#153A34",textAlign:"right"},withdraw:{backgroundColor:"#157A68",borderRadius:12,padding:14,alignItems:"center"},withdrawText:{color:"#FFF",fontWeight:"900"},row:{backgroundColor:"#FFF",borderRadius:12,padding:12,borderWidth:1,borderColor:"#D9E5E1"},rowMain:{color:"#193D36",fontWeight:"900",textAlign:"right"},rowSub:{color:"#71877F",fontSize:11,textAlign:"right",marginTop:4},error:{color:"#B42318",textAlign:"right",marginTop:8}});
