"use client";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
type W={user_id:string;coins:number;diamonds:number;updated_at:string};
type T={id:string;user_id:string;amount:number;balance_after:number|null;kind:string;currency:string;status:string;created_at:string};
type R={id:string;user_id:string;package_key:string;coins:number;bonus_coins:number;amount_usd:number;status:string;created_at:string};
type X={id:string;user_id:string;diamonds:number;amount_usd:number;method:string;status:string;admin_note:string|null;created_at:string};
export default function WalletPage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [wallets,setWallets]=useState<W[]>([]),[tx,setTx]=useState<T[]>([]),[recharges,setRecharges]=useState<R[]>([]),[withdraws,setWithdraws]=useState<X[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 async function load(){if(!supabase)return;setLoading(true);setError("");const [w,t,r,x]=await Promise.all([supabase.from("wallets").select("user_id,coins,diamonds,updated_at").order("coins",{ascending:false}).limit(100),supabase.from("wallet_transactions").select("id,user_id,amount,balance_after,kind,currency,status,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("recharge_orders").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("withdraw_requests").select("*").order("created_at",{ascending:false}).limit(100)]);const e=w.error||t.error||r.error||x.error;if(e)setError(e.message);else{setWallets((w.data??[]) as W[]);setTx((t.data??[]) as T[]);setRecharges((r.data??[]) as R[]);setWithdraws((x.data??[]) as X[])}setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 async function complete(id:string){if(!supabase)return;const {error}=await supabase.rpc("jehoo_admin_complete_recharge",{p_order_id:id});if(error)setError(error.message);else await load()}
 async function process(id:string,status:string){if(!supabase)return;const {error}=await supabase.rpc("jehoo_admin_process_withdraw",{p_request_id:id,p_status:status,p_note:status==="rejected"?"رفض من الإدارة":null});if(error)setError(error.message);else await load()}
 return <main className="main" dir="rtl"><div className="topbar"><div><a href="/" className="muted">JEHOO CHAT / لوحة التحكم</a><h1>المحافظ والاقتصاد</h1><p className="muted">Coins للشحن والإهداء، Diamonds للأرباح والسحب، وعمولات الوكالات منفصلة.</p></div><a className="secondary" href="/">رجوع</a></div>{error&&<div className="notice error">{error}</div>}{loading?<section className="panel">جارٍ التحميل…</section>:<><section className="panel" style={{marginBottom:20}}><h2>أعلى الأرصدة</h2>{wallets.map(w=><div key={w.user_id} style={{padding:"10px 0",borderBottom:"1px solid #263342"}}><strong>{Number(w.coins).toLocaleString("ar")} Coins</strong> · <strong>{Number(w.diamonds).toLocaleString("ar")} Diamonds</strong><div className="muted">{w.user_id}</div></div>)}{!wallets.length&&<p className="muted">لا توجد محافظ.</p>}</section>
 <section className="panel" style={{marginBottom:20}}><h2>طلبات الشحن</h2>{recharges.map(r=><div key={r.id} style={{padding:"10px 0",borderBottom:"1px solid #263342"}}><strong>{Number(r.coins+r.bonus_coins).toLocaleString("ar")} Coins</strong> · {"$"}{Number(r.amount_usd).toFixed(2)} · {r.status}<div className="muted">{r.user_id} · {new Date(r.created_at).toLocaleString("ar")}</div>{r.status==="pending"&&<button className="primary" onClick={()=>void complete(r.id)}>تأكيد الشحن</button>}</div>)}{!recharges.length&&<p className="muted">لا توجد طلبات.</p>}</section>
 <section className="panel" style={{marginBottom:20}}><h2>طلبات السحب</h2>{withdraws.map(x=><div key={x.id} style={{padding:"10px 0",borderBottom:"1px solid #263342"}}><strong>{Number(x.diamonds).toLocaleString("ar")} Diamonds</strong> · {"$"}{Number(x.amount_usd).toFixed(2)} · {x.method} · {x.status}<div className="muted">{x.user_id} · {new Date(x.created_at).toLocaleString("ar")}</div>{x.status==="pending"&&<div style={{display:"flex",gap:8,marginTop:8}}><button className="primary" onClick={()=>void process(x.id,"paid")}>تم الدفع</button><button className="secondary" onClick={()=>void process(x.id,"rejected")}>رفض</button></div>}</div>)}{!withdraws.length&&<p className="muted">لا توجد طلبات.</p>}</section>
 <section className="panel"><h2>آخر المعاملات</h2>{tx.map(t=><div key={t.id} style={{padding:"10px 0",borderBottom:"1px solid #263342"}}><strong>{t.amount>0?"+":""}{Number(t.amount).toLocaleString("ar")} {t.currency}</strong> · {t.kind} · {t.status}<div className="muted">{t.user_id} · {new Date(t.created_at).toLocaleString("ar")}</div></div>)}{!tx.length&&<p className="muted">لا توجد معاملات.</p>}</section></>}</main>
}