"use client";

import { useEffect, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase";

type Cosmetic={id:string;cosmetic_key:string;title:string;kind:"frame"|"name_effect"|"badge"|"entrance";asset_url:string|null;price:number;is_active:boolean};

const kinds:[Cosmetic["kind"],string][]=[["frame","إطار"],["name_effect","تأثير اسم"],["badge","شارة"],["entrance","دخول"]];

export default function CosmeticsPage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [rows,setRows]=useState<Cosmetic[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({cosmetic_key:"",title:"",kind:"frame" as Cosmetic["kind"],asset_url:"",price:100,is_active:true});
 async function load(){if(!supabase)return;setLoading(true);setError("");const {data,error}=await supabase.from("cosmetics_catalog").select("id,cosmetic_key,title,kind,asset_url,price,is_active").order("kind").order("price");if(error)setError(error.message);else setRows((data??[]) as Cosmetic[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 async function save(){if(!supabase)return;setSaving(true);setError("");if(!/^[a-z0-9_-]{2,50}$/.test(form.cosmetic_key.trim())){setError("مفتاح الكوزمتك غير صالح.");setSaving(false);return}const {error}=await supabase.from("cosmetics_catalog").upsert({cosmetic_key:form.cosmetic_key.trim(),title:form.title.trim(),kind:form.kind,asset_url:form.asset_url.trim()||null,price:Math.max(0,Math.floor(Number(form.price))),is_active:form.is_active},{onConflict:"cosmetic_key"});if(error)setError(error.message);else{setForm({cosmetic_key:"",title:"",kind:"frame",asset_url:"",price:100,is_active:true});await load()}setSaving(false)}
 async function toggle(row:Cosmetic){if(!supabase)return;const {error}=await supabase.from("cosmetics_catalog").update({is_active:!row.is_active}).eq("id",row.id);if(error)setError(error.message);else await load()}
 return <main className="main" dir="rtl"><div className="topbar"><div><a href="/" className="muted">JEHOO CHAT / لوحة التحكم</a><h1>الكوزمتكس</h1><p className="muted">إدارة الإطارات والشارات وتأثيرات الاسم والدخول.</p></div><a className="secondary" href="/">رجوع</a></div>{error&&<div className="notice error">{error}</div>}
 <section className="panel" style={{maxWidth:900,marginBottom:24}}><h2>إضافة / تحديث عنصر</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><div><label>Cosmetic Key</label><input className="field" value={form.cosmetic_key} onChange={e=>setForm({...form,cosmetic_key:e.target.value})} placeholder="frame_gold"/></div><div><label>الاسم</label><input className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="الإطار الذهبي"/></div><div><label>النوع</label><select className="field" value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as Cosmetic["kind"]})}>{kinds.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><label>السعر Coins</label><input className="field" type="number" min="0" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div><div style={{gridColumn:"1/-1"}}><label>رابط الصورة/الأصل (اختياري)</label><input className="field" value={form.asset_url} onChange={e=>setForm({...form,asset_url:e.target.value})} placeholder="https://..."/></div></div><label style={{display:"flex",gap:8,alignItems:"center",margin:"14px 0"}}><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> فعّال داخل التطبيق</label><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?"جارٍ الحفظ…":"حفظ العنصر"}</button></section>
 <section className="panel"><h2>الكتالوج الحالي</h2>{loading?<p>جارٍ التحميل…</p>:<div style={{display:"grid",gap:8}}>{rows.map(r=><div key={r.id} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:12,alignItems:"center",padding:"12px 0",borderBottom:"1px solid #263342"}}><div><strong>{r.title}</strong><div className="muted">{r.cosmetic_key} · {kinds.find(k=>k[0]===r.kind)?.[1]||r.kind} · {Number(r.price).toLocaleString("ar")} Coins</div></div><span className="pill">{r.is_active?"فعّال":"موقوف"}</span><button className="secondary" onClick={()=>void toggle(r)}>{r.is_active?"إيقاف":"تفعيل"}</button></div>)}{!rows.length&&<p className="muted">لا توجد عناصر.</p>}</div>}</section></main>
}