"use client";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
type A={id:string;owner_id:string;name:string;commission_percent:number;status:string};
type P={id:string;display_name:string;public_id:number};
export default function AgenciesPage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const [rows,setRows]=useState<A[]>([]),[profiles,setProfiles]=useState<P[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({name:"",owner_id:"",commission_percent:20});const [member,setMember]=useState({agency_id:"",user_id:"",role:"host"});
 async function load(){if(!supabase)return;const [a,p]=await Promise.all([supabase.from("agency_accounts").select("*").order("created_at",{ascending:false}),supabase.from("profiles").select("id,display_name,public_id").order("public_id",{ascending:true}).limit(500)]);if(a.error||p.error)setError((a.error||p.error)?.message||"تعذر التحميل");else{setRows((a.data??[]) as A[]);setProfiles((p.data??[]) as P[])}}
 useEffect(()=>{void load()},[supabase]);
 async function save(){if(!supabase)return;setSaving(true);setError("");const {error}=await supabase.from("agency_accounts").insert({name:form.name.trim(),owner_id:form.owner_id,commission_percent:Number(form.commission_percent)});if(error)setError(error.message);else{setForm({name:"",owner_id:"",commission_percent:20});await load()}setSaving(false)}
 async function addMember(){if(!supabase)return;setSaving(true);setError("");const {error}=await supabase.from("agency_members").upsert(member,{onConflict:"user_id"});if(error)setError(error.message);else{setMember({agency_id:"",user_id:"",role:"host"});await load()}setSaving(false)}
 async function toggle(a:A){if(!supabase)return;const {error}=await supabase.from("agency_accounts").update({status:a.status==="active"?"suspended":"active"}).eq("id",a.id);if(error)setError(error.message);else await load()}
 return <main className="main" dir="rtl">
 <div className="topbar"><div><a href="/" className="muted">JEHOO CHAT / لوحة التحكم</a><h1>الوكالات</h1><p className="muted">عمولة الوكالة تُضاف بشكل مستقل عن قيمة الهدية التي يستلمها المضيف.</p></div><a className="secondary" href="/">رجوع</a></div>
 {error&&<div className="notice error">{error}</div>}
 <section className="panel" style={{marginBottom:20}}><h2>إنشاء وكالة</h2><div style={{display:"grid",gridTemplateColumns:"2fr 2fr 1fr",gap:10}}><input className="field" placeholder="اسم الوكالة" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="field" value={form.owner_id} onChange={e=>setForm({...form,owner_id:e.target.value})}><option value="">اختر المالك</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.display_name||"مستخدم"} · {p.public_id}</option>)}</select><input className="field" type="number" min="0" max="100" value={form.commission_percent} onChange={e=>setForm({...form,commission_percent:Number(e.target.value)})}/></div><button className="primary" disabled={saving||!form.name||!form.owner_id} onClick={()=>void save()}>حفظ الوكالة</button></section>
 <section className="panel" style={{marginBottom:20}}><h2>إضافة عضو</h2><div style={{display:"grid",gridTemplateColumns:"2fr 2fr 1fr",gap:10}}><select className="field" value={member.agency_id} onChange={e=>setMember({...member,agency_id:e.target.value})}><option value="">اختر الوكالة</option>{rows.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className="field" value={member.user_id} onChange={e=>setMember({...member,user_id:e.target.value})}><option value="">اختر المستخدم</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.display_name||"مستخدم"} · {p.public_id}</option>)}</select><select className="field" value={member.role} onChange={e=>setMember({...member,role:e.target.value})}><option value="host">مضيف</option><option value="manager">مدير</option></select></div><button className="primary" disabled={saving||!member.agency_id||!member.user_id} onClick={()=>void addMember()}>إضافة العضو</button></section>
 <section className="panel"><h2>الوكالات الحالية</h2>{rows.map(a=><div key={a.id} style={{padding:"12px 0",borderBottom:"1px solid #263342"}}><strong>{a.name}</strong><div className="muted">Owner: {a.owner_id} · عمولة {a.commission_percent}% · {a.status}</div><button className="secondary" onClick={()=>void toggle(a)}>{a.status==="active"?"تعليق":"تفعيل"}</button></div>)}</section>
 </main>