"use client";
import {useEffect,useMemo,useState} from "react";
import {createSupabaseBrowserClient} from "@/lib/supabase";
type Event={id:string;title:string;description:string;image_url:string|null;starts_at:string;ends_at:string;is_active:boolean};
type Task={id:string;title:string;description:string;task_type:string;action_type:string;target_value:number;reward_coins:number;starts_at:string|null;ends_at:string|null;is_active:boolean};
export default function EventsPage(){
 const supabase=useMemo(()=>createSupabaseBrowserClient(),[]); const [events,setEvents]=useState<Event[]>([]),[tasks,setTasks]=useState<Task[]>([]),[tab,setTab]=useState<"events"|"tasks">("events"),[error,setError]=useState("");
 const [event,setEvent]=useState({title:"",description:"",starts_at:"",ends_at:"",image_url:"",is_active:true});
 const [task,setTask]=useState({title:"",description:"",task_type:"daily",action_type:"room_join",target_value:1,reward_coins:100,starts_at:"",ends_at:"",is_active:true});
 async function load(){const a=await supabase.from("app_events").select("*").order("starts_at",{ascending:false});const b=await supabase.from("app_tasks").select("*").order("created_at",{ascending:false});if(a.error||b.error)setError(a.error?.message||b.error?.message||"");else{setEvents((a.data??[]) as Event[]);setTasks((b.data??[]) as Task[])}}
 useEffect(()=>{void load()},[]);
 async function saveEvent(){setError("");const {error:e}=await supabase.from("app_events").insert({...event,starts_at:new Date(event.starts_at).toISOString(),ends_at:new Date(event.ends_at).toISOString(),image_url:event.image_url||null});if(e)setError(e.message);else{setEvent({title:"",description:"",starts_at:"",ends_at:"",image_url:"",is_active:true});await load()}}
 async function saveTask(){setError("");const {error:e}=await supabase.from("app_tasks").insert({...task,target_value:Math.max(1,Number(task.target_value)),reward_coins:Math.max(0,Number(task.reward_coins)),starts_at:task.starts_at?new Date(task.starts_at).toISOString():null,ends_at:task.ends_at?new Date(task.ends_at).toISOString():null});if(e)setError(e.message);else{setTask({title:"",description:"",task_type:"daily",target_value:1,reward_coins:100,starts_at:"",ends_at:"",is_active:true});await load()}}
 return <main className="main" dir="rtl"><div className="topbar"><div><a href="/" className="muted">JEHOO CHAT / لوحة التحكم</a><h1>الفعاليات والمهام</h1><p className="muted">إنشاء فعاليات ومهام ومكافآت Coins.</p></div><a className="secondary" href="/">رجوع</a></div>{error&&<div className="notice error">{error}</div>}
 <div style={{display:"flex",gap:8,marginBottom:16}}><button className={tab==="events"?"primary":"secondary"} onClick={()=>setTab("events")}>الفعاليات</button><button className={tab==="tasks"?"primary":"secondary"} onClick={()=>setTab("tasks")}>المهام</button></div>
 {tab==="events"?<><section className="panel" style={{marginBottom:20}}><h2>فعالية جديدة</h2><div style={{display:"grid",gap:10}}><input className="field" placeholder="العنوان" value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/><textarea className="field" placeholder="الوصف" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/><input className="field" placeholder="رابط الصورة (اختياري)" value={event.image_url} onChange={e=>setEvent({...event,image_url:e.target.value})}/><input className="field" type="datetime-local" value={event.starts_at} onChange={e=>setEvent({...event,starts_at:e.target.value})}/><input className="field" type="datetime-local" value={event.ends_at} onChange={e=>setEvent({...event,ends_at:e.target.value})}/><button className="primary" onClick={()=>void saveEvent()}>حفظ الفعالية</button></div></section><section className="panel"><h2>الفعاليات</h2>{events.map(x=><div key={x.id} style={{padding:12,borderBottom:"1px solid #263342"}}><strong>{x.title}</strong><div className="muted">{new Date(x.starts_at).toLocaleString("ar")} → {new Date(x.ends_at).toLocaleString("ar")}</div><div>{x.description}</div></div>)}</section></>:
 <><section className="panel" style={{marginBottom:20}}><h2>مهمة جديدة</h2><div style={{display:"grid",gap:10}}><input className="field" placeholder="العنوان" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><textarea className="field" placeholder="الوصف" value={task.description} onChange={e=>setTask({...task,description:e.target.value})}/><select className="field" value={task.task_type} onChange={e=>setTask({...task,task_type:e.target.value})}><option value="daily">يومية</option><option value="weekly">أسبوعية</option><option value="event">فعالية</option></select><select className="field" value={task.action_type} onChange={e=>setTask({...task,action_type:e.target.value})}><option value="room_join">دخول غرفة</option><option value="message_sent">إرسال رسالة</option><option value="gift_sent">إرسال هدية</option><option value="gift_received">استلام هدية</option></select><input className="field" type="number" min="1" placeholder="الهدف" value={task.target_value} onChange={e=>setTask({...task,target_value:Number(e.target.value)})}/><input className="field" type="number" min="0" placeholder="مكافأة Coins" value={task.reward_coins} onChange={e=>setTask({...task,reward_coins:Number(e.target.value)})}/><button className="primary" onClick={()=>void saveTask()}>حفظ المهمة</button></div></section><section className="panel"><h2>المهام</h2>{tasks.map(x=><div key={x.id} style={{padding:12,borderBottom:"1px solid #263342"}}><strong>{x.title}</strong><div className="muted">{x.task_type} · {x.action_type} · الهدف {x.target_value} · المكافأة {x.reward_coins} Coins</div><div>{x.description}</div></div>)}</section></>}</main>
}